### ISSUE TITLE
Can't build dub projects with ldc in 24.08 - "undefined symbol: LLVMInitializeWebAssemblyTarget, version LLVM_18.1"

### ISSUE THREAD

**Issue by grillo-delmal** [flathub/org.freedesktop.Sdk.Extension.ldc#91]
Was trying to build a bigger flatpak project and stumbled on this. 

Here is a small example file that reproduces the problem

```yml
id: test.test.test
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm18
  - org.freedesktop.Sdk.Extension.ldc

modules:
  - name: test
    buildsystem: simple
    build-options:
      append-path: /usr/lib/sdk/ldc/bin
    build-commands:
      - dub build
    sources:
      - type: "archive"
        url: "https://code.dlang.org/packages/ping/0.0.5.zip"
        sha256: "8e543b98af571e38cc73868884d55ef60e9c5aa66641e93513474cc401101676"
```

```sh
flatpak-builder --default-branch=localbuild --force-clean --repo=./repo-dir ./build-dir test.test.test.yml
```

This fails with the following output

```sh
Downloading sources
Downloading https://code.dlang.org/packages/ping/0.0.5.zip
...
Initializing build dir
Committing stage init to cache
Starting build of test.test.test
========================================================================
Building module test in /home/grillo/src/tests/ldc-test/.flatpak-builder/build/test-1
========================================================================
Running: dub build
Error Failed to invoke the compiler /usr/lib/sdk/ldc/bin/ldc2 to determine the build platform: /usr/lib/sdk/ldc/bin/ldc2: symbol lookup error: /usr/lib/sdk/ldc/bin/ldc2: undefined symbol: LLVMInitializeWebAssemblyTarget, version LLVM_18.1

Error: module test: Child process exited with code 2
```
